from .entry import BenchlingEntry, BenchlingEntryList  # NOQA F401
from .resource import RESOURCE_MAP, BenchlingResource, BenchlingResourceURI  # NOQA F401
from .root import BenchlingById, BenchlingRoot  # NOQA F401
from .schema import BenchlingSchema, BenchlingSchemaList  # NOQA F401
from .sequence import BenchlingSequence, BenchlingSequenceList  # NOQA F401

RESOURCES = [
    "aa_sequences",
    "api",
    "apps",
    "assay_results",
    "assay_runs",
    "blobs",
    "boxes",
    "client",
    "containers",
    "custom_entities",
    "dna_alignments",
    "dna_oligos",
    "dna_sequences",
    "dropdowns",
    "entries",
    "events",
    "exports",
    "feature_libraries",
    "folders",
    "inventory",
    "lab_automation",
    "label_templates",
    "locations",
    "mixtures",
    "molecules",
    "nucleotide_alignments",
    "oligos",
    "organizations",
    "plates",
    "printers",
    "projects",
    "registry",
    "requests",
    "rna_oligos",
    "rna_sequences",
    "schemas",
    "tasks",
    "teams",
    "users",
    "v2",
    "warehouse",
    "workflow_outputs",
    "workflow_task_groups",
    "workflow_tasks",
]
